# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

receive_arrow_table_from_python <- function(python_ref) {
    .Call('_RcppPyArrow_receive_arrow_table_from_python', PACKAGE = 'RcppPyArrow', python_ref)
}

